# Generated by Django 5.0.6 on 2024-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalyst_builder_app', '0002_companydata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='current_employee_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_employee_estimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='year_founded',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
